// Each six-word semantic cluster yields six cards. For each card, the other five
// terms become the forbidden words. Cards are deduplicated by target below.
export const WORD_CLUSTERS = [
  ["Places", ["Kitchen", "Oven", "Stove", "Refrigerator", "Sink", "Countertop"]],
  ["Places", ["Bedroom", "Bed", "Pillow", "Blanket", "Mattress", "Alarm clock"]],
  ["Places", ["Bathroom", "Shower", "Toilet", "Bathtub", "Towel", "Mirror"]],
  ["Places", ["Living room", "Sofa", "Television", "Coffee table", "Fireplace", "Remote control"]],
  ["Places", ["Laundry room", "Washing machine", "Dryer", "Detergent", "Hamper", "Fabric softener"]],
  ["Places", ["Cleaning closet", "Vacuum", "Mop", "Broom", "Dustpan", "Sponge"]],
  ["Places", ["Backyard", "Patio", "Fence", "Lawn", "Sprinkler", "Hammock"]],
  ["Places", ["Garage", "Toolbox", "Workbench", "Car jack", "Door opener", "Motor oil"]],
  ["Places", ["Office", "Desk", "Swivel chair", "Stapler", "Printer", "Filing cabinet"]],
  ["Places", ["Classroom", "Teacher", "Student", "Whiteboard", "Homework", "Textbook"]],
  ["Places", ["Library", "Librarian", "Bookshelf", "Quiet", "Library card", "Borrow"]],
  ["Places", ["Hospital", "Doctor", "Nurse", "Patient", "Ambulance", "Surgery"]],
  ["Places", ["Restaurant", "Menu", "Waiter", "Chef", "Reservation", "Tip"]],
  ["Places", ["Hotel", "Lobby", "Receptionist", "Room key", "Elevator", "Checkout"]],
  ["Places", ["Airport", "Airplane", "Passport", "Luggage", "Security", "Runway"]],
  ["Places", ["Grocery store", "Shopping cart", "Aisle", "Cashier", "Receipt", "Checkout line"]],
  ["Places", ["Bank", "Teller", "Vault", "Account", "Loan", "Deposit"]],
  ["Places", ["Post office", "Stamp", "Envelope", "Mailbox", "Package", "Postcard"]],
  ["Places", ["Courthouse", "Judge", "Jury", "Lawyer", "Trial", "Verdict"]],
  ["Places", ["Fire station", "Firefighter", "Fire truck", "Hose", "Siren", "Helmet"]],
  ["Places", ["Police station", "Officer", "Badge", "Handcuffs", "Patrol car", "Suspect"]],
  ["Places", ["Theater", "Stage", "Actor", "Audience", "Curtain", "Applause"]],
  ["Places", ["Museum", "Exhibit", "Artifact", "Gallery", "Curator", "Admission"]],
  ["Places", ["Zoo", "Zookeeper", "Enclosure", "Safari", "Habitat", "Feeding time"]],
  ["Places", ["Farm", "Tractor", "Barn", "Crop", "Farmer", "Field"]],
  ["Places", ["Construction site", "Crane", "Hard hat", "Scaffolding", "Concrete", "Blueprint"]],
  ["Places", ["Hardware store", "Hammer", "Power drill", "Nails", "Measuring tape", "Lumber"]],
  ["Places", ["Barbershop", "Haircut", "Clippers", "Scissors", "Razor", "Barber chair"]],
  ["Places", ["Beauty salon", "Stylist", "Shampoo", "Hair dryer", "Manicure", "Appointment"]],
  ["Places", ["Gym", "Treadmill", "Weights", "Trainer", "Locker room", "Membership"]],
  ["Places", ["Playground", "Swing", "Slide", "Sandbox", "Jungle gym", "Seesaw"]],
  ["Places", ["Campsite", "Tent", "Campfire", "Sleeping bag", "Lantern", "Hiking trail"]],
  ["Places", ["Train station", "Platform", "Conductor", "Ticket", "Railroad", "Timetable"]],
  ["Places", ["Subway", "Metro card", "Turnstile", "Underground", "Rush hour", "Train car"]],
  ["Places", ["Gas station", "Fuel pump", "Gasoline", "Nozzle", "Car wash", "Convenience store"]],

  ["Food", ["Coffee", "Espresso", "Caffeine", "Mug", "Brew", "Coffee beans"]],
  ["Food", ["Tea", "Teapot", "Kettle", "Tea bag", "Herbal", "Steep"]],
  ["Food", ["Pizza", "Cheese", "Pepperoni", "Crust", "Slice", "Delivery"]],
  ["Food", ["Hamburger", "Bun", "Beef patty", "Ketchup", "Pickles", "French fries"]],
  ["Food", ["Sushi", "Rice", "Seaweed", "Raw fish", "Chopsticks", "Wasabi"]],
  ["Food", ["Taco", "Tortilla", "Salsa", "Guacamole", "Ground beef", "Tuesday"]],
  ["Food", ["Spaghetti", "Pasta sauce", "Meatballs", "Noodles", "Parmesan", "Fork"]],
  ["Food", ["Breakfast", "Bacon", "Eggs", "Toast", "Morning", "Orange juice"]],
  ["Food", ["Sandwich", "Bread", "Mayonnaise", "Deli meat", "Lettuce", "Lunch"]],
  ["Food", ["Salad", "Dressing", "Croutons", "Greens", "Bowl", "Healthy"]],
  ["Food", ["Soup", "Broth", "Spoon", "Pot", "Chicken noodle", "Warm"]],
  ["Food", ["Ice cream", "Cone", "Scoop", "Freezer", "Sprinkles", "Sundae"]],
  ["Food", ["Chocolate", "Cocoa", "Candy bar", "Sweet", "Dark", "Milk chocolate"]],
  ["Food", ["Birthday cake", "Candles", "Frosting", "Wish", "Party", "Slice"]],
  ["Food", ["Cheeseboard", "Crackers", "Brie", "Gouda", "Grapes", "Charcuterie"]],
  ["Food", ["Apple", "Orchard", "Core", "Pie", "Red", "Cider"]],
  ["Food", ["Banana", "Peel", "Yellow", "Monkey", "Bunch", "Smoothie"]],
  ["Food", ["Lemon", "Sour", "Citrus", "Lemonade", "Zest", "Wedge"]],
  ["Food", ["Steak", "Rare", "Grill", "Sirloin", "Knife", "Medium"]],
  ["Food", ["Barbecue", "Smoker", "Ribs", "Sauce", "Charcoal", "Cookout"]],
  ["Food", ["Popcorn", "Movie", "Kernel", "Butter", "Microwave", "Bucket"]],
  ["Food", ["Cookies", "Chocolate chips", "Baking sheet", "Dough", "Milk", "Jar"]],
  ["Food", ["Cereal", "Breakfast bowl", "Corn flakes", "Box", "Soggy", "Spoon"]],
  ["Food", ["Pancakes", "Syrup", "Stack", "Griddle", "Fluffy", "Flip"]],
  ["Food", ["Spices", "Pepper", "Paprika", "Cinnamon", "Seasoning", "Rack"]],
  ["Food", ["Bakery", "Croissant", "Flour", "Pastry", "Loaf", "Baker"]],
  ["Food", ["Winery", "Vineyard", "Grapes", "Bottle", "Sommelier", "Tasting"]],
  ["Food", ["Beer", "Brewery", "Hops", "Pint", "Foam", "Tap"]],
  ["Food", ["Cocktail", "Bartender", "Shaker", "Garnish", "Martini", "Happy hour"]],
  ["Food", ["Food truck", "Street food", "Window", "Order", "Festival", "Mobile kitchen"]],

  ["Animals", ["Dog", "Puppy", "Leash", "Bark", "Kennel", "Fetch"]],
  ["Animals", ["Cat", "Kitten", "Whiskers", "Purr", "Litter box", "Scratch"]],
  ["Animals", ["Horse", "Saddle", "Gallop", "Stable", "Reins", "Mane"]],
  ["Animals", ["Cow", "Calf", "Pasture", "Moo", "Cattle", "Dairy"]],
  ["Animals", ["Pig", "Snout", "Pork", "Mud", "Sty", "Oink"]],
  ["Animals", ["Chicken", "Hen", "Rooster", "Coop", "Egg", "Cluck"]],
  ["Animals", ["Sheep", "Wool", "Lamb", "Flock", "Shepherd", "Fleece"]],
  ["Animals", ["Goat", "Horn", "Beard", "Kid", "Herd", "Bleat"]],
  ["Animals", ["Lion", "Mane", "Roar", "Pride", "Savanna", "Cub"]],
  ["Animals", ["Tiger", "Stripes", "Jungle", "Predator", "Feline", "Pounce"]],
  ["Animals", ["Elephant", "Trunk", "Tusk", "Ivory", "Giant", "Stampede"]],
  ["Animals", ["Giraffe", "Long neck", "Spots", "Tall", "Acacia", "Africa"]],
  ["Animals", ["Chimpanzee", "Primate", "Banana", "Swing", "Knuckles", "Troop"]],
  ["Animals", ["Gorilla", "Silverback", "Chest", "Ape", "Rainforest", "Powerful"]],
  ["Animals", ["Kangaroo", "Pouch", "Australia", "Hop", "Joey", "Boxing"]],
  ["Animals", ["Koala", "Eucalyptus", "Tree", "Marsupial", "Sleep", "Australia"]],
  ["Animals", ["Panda", "Bamboo", "China", "Black and white", "Bear", "Endangered"]],
  ["Animals", ["Polar bear", "Arctic", "Ice", "White fur", "Seal", "North Pole"]],
  ["Animals", ["Penguin", "Antarctica", "Tuxedo", "Waddle", "Flippers", "Colony"]],
  ["Animals", ["Owl", "Night", "Hoot", "Wide eyes", "Wise", "Perch"]],
  ["Animals", ["Eagle", "Talons", "Bald", "Nest", "Soar", "Freedom"]],
  ["Animals", ["Flamingo", "Pink", "One leg", "Flock", "Beak", "Lagoon"]],
  ["Animals", ["Peacock", "Feathers", "Tail fan", "Colorful", "Proud", "Bird"]],
  ["Animals", ["Duck", "Quack", "Pond", "Webbed feet", "Duckling", "Bill"]],
  ["Animals", ["Shark", "Fin", "Teeth", "Ocean", "Predator", "Jaws"]],
  ["Animals", ["Dolphin", "Sonar", "Pod", "Intelligent", "Flipper", "Leap"]],
  ["Animals", ["Whale", "Blowhole", "Baleen", "Ocean giant", "Song", "Migrate"]],
  ["Animals", ["Octopus", "Tentacles", "Eight", "Ink", "Suction cups", "Camouflage"]],
  ["Animals", ["Jellyfish", "Sting", "Tentacles", "Transparent", "Float", "Ocean"]],
  ["Animals", ["Sea turtle", "Shell", "Flippers", "Reef", "Hatchling", "Long-lived"]],
  ["Animals", ["Crocodile", "Swamp", "Teeth", "Reptile", "Snout", "River"]],
  ["Animals", ["Snake", "Slither", "Venom", "Scales", "Fangs", "Shed"]],
  ["Animals", ["Frog", "Tadpole", "Pond", "Croak", "Tongue", "Amphibian"]],
  ["Animals", ["Butterfly", "Caterpillar", "Cocoon", "Wings", "Metamorphosis", "Nectar"]],
  ["Animals", ["Honeybee", "Hive", "Honey", "Queen", "Stinger", "Pollen"]],

  ["Nature", ["Rain", "Umbrella", "Cloud", "Puddle", "Drizzle", "Wet"]],
  ["Nature", ["Snow", "Snowflake", "Winter", "Shovel", "Blizzard", "Cold"]],
  ["Nature", ["Thunderstorm", "Lightning", "Thunder", "Dark clouds", "Downpour", "Forecast"]],
  ["Nature", ["Tornado", "Funnel", "Twister", "Storm cellar", "Wind", "Siren"]],
  ["Nature", ["Hurricane", "Eye", "Evacuation", "Coast", "Category", "Storm surge"]],
  ["Nature", ["Rainbow", "Colors", "Rain", "Sunshine", "Arc", "Pot of gold"]],
  ["Nature", ["Volcano", "Lava", "Eruption", "Magma", "Crater", "Ash"]],
  ["Nature", ["Earthquake", "Fault line", "Tremor", "Magnitude", "Shake", "Epicenter"]],
  ["Nature", ["Desert", "Sand", "Cactus", "Dunes", "Dry", "Oasis"]],
  ["Nature", ["Rainforest", "Canopy", "Humid", "Jungle", "Biodiversity", "Tropical"]],
  ["Nature", ["Ocean", "Saltwater", "Waves", "Deep", "Tide", "Current"]],
  ["Nature", ["River", "Stream", "Bank", "Flow", "Bridge", "Downstream"]],
  ["Nature", ["Mountain", "Peak", "Climb", "Summit", "Altitude", "Range"]],
  ["Nature", ["Beach", "Sandcastle", "Waves", "Seashell", "Sunbathe", "Towel"]],
  ["Nature", ["Waterfall", "Cliff", "Cascade", "Mist", "Plunge", "Pool"]],
  ["Nature", ["Cave", "Stalactite", "Underground", "Bat", "Dark", "Cavern"]],
  ["Nature", ["Island", "Surrounded", "Tropical", "Palm tree", "Boat", "Shore"]],
  ["Nature", ["Glacier", "Iceberg", "Frozen", "Melt", "Crevasse", "Climate"]],
  ["Nature", ["Sun", "Solar", "Heat", "Daylight", "Star", "Sunrise"]],
  ["Nature", ["Moon", "Night sky", "Crescent", "Crater", "Orbit", "Full moon"]],
  ["Nature", ["Mars", "Red planet", "Rover", "Dust", "Olympus Mons", "Space mission"]],
  ["Nature", ["Saturn", "Rings", "Gas giant", "Titan", "Planet", "Cassini"]],
  ["Nature", ["Forest", "Trees", "Woodland", "Trail", "Pine", "Clearing"]],
  ["Nature", ["Meadow", "Wildflowers", "Grass", "Field", "Butterflies", "Pasture"]],
  ["Nature", ["Autumn", "Leaves", "Orange", "Harvest", "Fall", "October"]],

  ["Culture", ["Rock music", "Electric guitar", "Drums", "Band", "Concert", "Amplifier"]],
  ["Culture", ["Jazz", "Saxophone", "Improvisation", "Swing", "Blue note", "Trumpet"]],
  ["Culture", ["Classical music", "Orchestra", "Composer", "Symphony", "Conductor", "Violin"]],
  ["Culture", ["Hip-hop", "Rapper", "Beat", "Rhymes", "Turntable", "Mic"]],
  ["Culture", ["Country music", "Nashville", "Cowboy", "Guitar", "Honky-tonk", "Banjo"]],
  ["Culture", ["Piano", "Keyboard", "Keys", "Pedal", "Grand", "Chopin"]],
  ["Culture", ["Violin", "Bow", "Strings", "Chin rest", "Fiddle", "Orchestra"]],
  ["Culture", ["Drum set", "Drumsticks", "Snare", "Cymbal", "Rhythm", "Percussion"]],
  ["Culture", ["Movie theater", "Screen", "Popcorn", "Trailer", "Seat", "Projector"]],
  ["Culture", ["Comedy film", "Funny", "Laugh", "Joke", "Actor", "Punchline"]],
  ["Culture", ["Horror film", "Scary", "Monster", "Scream", "Haunted", "Jump scare"]],
  ["Culture", ["Science fiction", "Spaceship", "Alien", "Future", "Robot", "Galaxy"]],
  ["Culture", ["Documentary", "Real life", "Interview", "Facts", "Narrator", "Footage"]],
  ["Culture", ["Detective novel", "Mystery", "Clue", "Murder", "Suspect", "Solution"]],
  ["Culture", ["Fantasy novel", "Magic", "Dragon", "Quest", "Kingdom", "Wizard"]],
  ["Culture", ["Poetry", "Rhyme", "Verse", "Stanza", "Metaphor", "Poet"]],
  ["Culture", ["Newspaper", "Headline", "Reporter", "Article", "Press", "Daily"]],
  ["Culture", ["Podcast", "Episode", "Host", "Microphone", "Subscribe", "Audio"]],
  ["Culture", ["Radio", "Station", "Antenna", "Broadcast", "DJ", "Frequency"]],
  ["Culture", ["Photography", "Camera", "Lens", "Portrait", "Shutter", "Exposure"]],
  ["Culture", ["Painting", "Canvas", "Brush", "Palette", "Artist", "Gallery"]],
  ["Culture", ["Sculpture", "Statue", "Marble", "Chisel", "Museum", "Three-dimensional"]],
  ["Culture", ["Ballet", "Dancer", "Tutu", "Pointe shoes", "Pirouette", "Stage"]],
  ["Culture", ["Magic trick", "Magician", "Rabbit", "Hat", "Illusion", "Card"]],
  ["Culture", ["Circus", "Clown", "Tent", "Acrobat", "Ringmaster", "Trapeze"]],
  ["Culture", ["Board game", "Dice", "Pieces", "Rules", "Winner", "Tabletop"]],
  ["Culture", ["Chess", "King", "Queen", "Checkmate", "Pawn", "Board"]],
  ["Culture", ["Playing cards", "Deck", "Ace", "Shuffle", "Suit", "Dealer"]],
  ["Culture", ["Video game", "Controller", "Console", "Level", "Player", "Score"]],
  ["Culture", ["Karaoke", "Lyrics", "Sing", "Microphone", "Bar", "Off-key"]],

  ["Sports", ["Soccer", "Goal", "Pitch", "Striker", "Goalkeeper", "World Cup"]],
  ["Sports", ["Basketball", "Hoop", "Dribble", "Court", "Three-pointer", "NBA"]],
  ["Sports", ["Baseball", "Bat", "Pitcher", "Home run", "Diamond", "Inning"]],
  ["Sports", ["American football", "Touchdown", "Quarterback", "Helmet", "End zone", "NFL"]],
  ["Sports", ["Ice hockey", "Puck", "Stick", "Rink", "Goalie", "Penalty box"]],
  ["Sports", ["Tennis", "Racket", "Serve", "Net", "Wimbledon", "Love"]],
  ["Sports", ["Golf", "Club", "Hole", "Caddie", "Par", "Green"]],
  ["Sports", ["Boxing", "Ring", "Gloves", "Punch", "Knockout", "Round"]],
  ["Sports", ["Swimming", "Pool", "Goggles", "Lap", "Freestyle", "Dive"]],
  ["Sports", ["Gymnastics", "Balance beam", "Vault", "Floor routine", "Leotard", "Flip"]],
  ["Sports", ["Marathon", "Runner", "26.2 miles", "Finish line", "Race", "Endurance"]],
  ["Sports", ["Cycling", "Bicycle", "Pedal", "Helmet", "Tour de France", "Road"]],
  ["Sports", ["Skiing", "Snow", "Slope", "Poles", "Mountain", "Chairlift"]],
  ["Sports", ["Surfing", "Board", "Wave", "Ocean", "Wetsuit", "Beach"]],
  ["Sports", ["Bowling", "Pins", "Lane", "Strike", "Ball", "Spare"]],
  ["Sports", ["Pool table", "Cue", "Billiards", "Eight ball", "Pocket", "Chalk"]],
  ["Sports", ["Darts", "Bullseye", "Target", "Pub", "Throw", "Board"]],
  ["Sports", ["Poker", "Chips", "Bluff", "Hand", "Bet", "Royal flush"]],
  ["Sports", ["Hide-and-seek", "Count", "Find", "Hiding place", "Ready or not", "Tag"]],
  ["Sports", ["Hopscotch", "Sidewalk", "Chalk", "Squares", "Jump", "Playground"]],

  ["Science", ["Computer", "Keyboard", "Monitor", "Mouse", "Processor", "Laptop"]],
  ["Science", ["Smartphone", "App", "Touchscreen", "Text message", "Charger", "Cellular"]],
  ["Science", ["Internet", "Website", "Browser", "Online", "Wi-Fi", "Search engine"]],
  ["Science", ["Email", "Inbox", "Attachment", "Spam", "Send", "Address"]],
  ["Science", ["Password", "Login", "Secret", "Username", "Security", "Reset"]],
  ["Science", ["Social media", "Followers", "Post", "Like", "Feed", "Hashtag"]],
  ["Science", ["Artificial intelligence", "Machine learning", "Algorithm", "Chatbot", "Data", "Neural network"]],
  ["Science", ["Robot", "Machine", "Automation", "Android", "Program", "Metal"]],
  ["Science", ["Virtual reality", "Headset", "Immersive", "Simulation", "Goggles", "Avatar"]],
  ["Science", ["3D printer", "Filament", "Layer", "Model", "Plastic", "Prototype"]],
  ["Science", ["Electric car", "Battery", "Charging station", "Tesla", "Motor", "Emissions"]],
  ["Science", ["Drone", "Remote control", "Propeller", "Camera", "Fly", "Aerial"]],
  ["Science", ["Telescope", "Stars", "Lens", "Observatory", "Astronomy", "Magnify"]],
  ["Science", ["Microscope", "Slide", "Tiny", "Magnification", "Laboratory", "Cells"]],
  ["Science", ["Laboratory", "Experiment", "Test tube", "Scientist", "Chemicals", "Research"]],
  ["Science", ["Gravity", "Fall", "Earth", "Newton", "Force", "Weight"]],
  ["Science", ["Electricity", "Current", "Voltage", "Power", "Outlet", "Shock"]],
  ["Science", ["Magnet", "Attract", "Repel", "North", "Metal", "Field"]],
  ["Science", ["Atom", "Nucleus", "Electron", "Proton", "Tiny", "Element"]],
  ["Science", ["DNA", "Genes", "Double helix", "Chromosome", "Genetics", "Cell"]],
  ["Science", ["Dinosaur", "Fossil", "Extinct", "Jurassic", "Bones", "Paleontologist"]],
  ["Science", ["Astronaut", "Space suit", "Rocket", "NASA", "Orbit", "Moon"]],
  ["Science", ["Satellite", "Orbit", "Signal", "Space", "Dish", "Communication"]],
  ["Science", ["Rocket", "Launch", "Engine", "Countdown", "Spacecraft", "Fuel"]],
  ["Science", ["Solar panel", "Sunlight", "Energy", "Roof", "Electricity", "Renewable"]],
  ["Science", ["Wind turbine", "Blades", "Wind farm", "Generator", "Renewable", "Tower"]],
  ["Science", ["Recycling", "Plastic", "Paper", "Bin", "Reuse", "Waste"]],
  ["Science", ["Climate change", "Global warming", "Carbon", "Temperature", "Emissions", "Planet"]],
  ["Science", ["Medicine", "Prescription", "Pharmacy", "Pill", "Dose", "Treatment"]],
  ["Science", ["X-ray", "Bones", "Radiation", "Hospital", "Image", "Broken"]],

  ["Life", ["Wedding", "Bride", "Groom", "Ring", "Ceremony", "Marriage"]],
  ["Life", ["Birthday", "Cake", "Candles", "Age", "Present", "Celebrate"]],
  ["Life", ["Graduation", "Diploma", "Cap and gown", "School", "Ceremony", "Degree"]],
  ["Life", ["Vacation", "Travel", "Hotel", "Relax", "Suitcase", "Time off"]],
  ["Life", ["Job interview", "Résumé", "Questions", "Hiring", "Suit", "Employer"]],
  ["Life", ["First date", "Romance", "Dinner", "Nervous", "Couple", "Restaurant"]],
  ["Life", ["Family reunion", "Relatives", "Gathering", "Cousins", "Photo", "Picnic"]],
  ["Life", ["Baby shower", "Pregnant", "Gifts", "Diapers", "Newborn", "Party"]],
  ["Life", ["Surprise party", "Secret", "Hide", "Guests", "Shout", "Birthday"]],
  ["Life", ["Road trip", "Car", "Highway", "Map", "Snacks", "Destination"]],
  ["Life", ["Morning routine", "Wake up", "Brush teeth", "Breakfast", "Shower", "Alarm"]],
  ["Life", ["Bedtime", "Sleep", "Pajamas", "Brush teeth", "Story", "Lights out"]],
  ["Life", ["Shopping", "Buy", "Store", "Money", "Bag", "Sale"]],
  ["Life", ["Cooking", "Recipe", "Ingredients", "Chop", "Pan", "Meal"]],
  ["Life", ["Dancing", "Music", "Rhythm", "Moves", "Floor", "Partner"]],
  ["Life", ["Singing", "Voice", "Song", "Lyrics", "Melody", "Choir"]],
  ["Life", ["Laughter", "Funny", "Smile", "Joke", "Giggle", "Comedy"]],
  ["Life", ["Crying", "Tears", "Sad", "Eyes", "Emotion", "Sobbing"]],
  ["Life", ["Anger", "Mad", "Furious", "Temper", "Shout", "Red"]],
  ["Life", ["Fear", "Scared", "Afraid", "Danger", "Panic", "Nightmare"]],
  ["Life", ["Jealousy", "Envy", "Possessive", "Green", "Rival", "Want"]],
  ["Life", ["Patience", "Wait", "Calm", "Time", "Tolerance", "Hurry"]],
  ["Life", ["Curiosity", "Question", "Wonder", "Explore", "Interested", "Discover"]],
  ["Life", ["Luck", "Chance", "Fortune", "Lucky charm", "Coincidence", "Gamble"]],
  ["Life", ["Secret", "Whisper", "Private", "Tell", "Confidential", "Keep"]]
];

export function buildCards(clusters = WORD_CLUSTERS) {
  const seen = new Set();
  const cards = [];

  clusters.forEach(([category, words], groupIndex) => {
    words.forEach((target, wordIndex) => {
      const key = target.toLocaleLowerCase();
      if (seen.has(key)) return;
      seen.add(key);
      cards.push({
        id: `${groupIndex + 1}-${wordIndex + 1}`,
        target,
        forbidden: words.filter((_, index) => index !== wordIndex),
        category
      });
    });
  });

  return cards;
}

export const CARDS = Object.freeze(buildCards().map((card) => Object.freeze(card)));
export const CARD_COUNT = CARDS.length;
