// Broad, familiar prompts give a group room to keep the letters moving.
const PROMPTS = Object.freeze([
  "Types of food",
  "Fast food restaurants",
  "Pizza toppings",
  "Ice cream flavors",
  "Breakfast foods",
  "Snack foods",
  "Candy",
  "Desserts",
  "Fruit",
  "Vegetables",
  "Cheeses",
  "Types of bread",
  "Sandwich fillings",
  "Things in a salad",
  "Things on a burger",
  "Pasta dishes",
  "Soups",
  "Sauces and condiments",
  "Herbs and spices",
  "Drinks",
  "Coffee drinks",
  "Foods you eat with your hands",
  "Foods served cold",
  "Foods you dip",
  "Foods on a stick",
  "Things at a bakery",
  "Things at a barbecue",
  "Things at a grocery store",
  "Restaurant chains",
  "Cereals",
  "Animals",
  "Pets",
  "Farm animals",
  "Sea creatures",
  "Birds",
  "Insects",
  "Dinosaurs",
  "Dog breeds",
  "Animals with stripes or spots",
  "Animals that can fly",
  "Animals you might see at a zoo",
  "Things found in the ocean",
  "Things in a forest",
  "Things in a garden",
  "Flowers",
  "Trees",
  "Things that grow on trees",
  "Things in the sky",
  "Weather words",
  "Things that float",
  "Things that are green",
  "Things that are round",
  "Things that are soft",
  "Things that are loud",
  "Things that smell good",
  "Things that sparkle",
  "Things made of wood",
  "Things made of metal",
  "Things made of glass",
  "Things that need batteries",
  "Things with wheels",
  "Things with buttons",
  "Things with a handle",
  "Things with a screen",
  "Things you can fold",
  "Things you can collect",
  "Things you can build",
  "Things you can wear",
  "Shoes",
  "Hats",
  "Things in a backpack",
  "Things in a kitchen",
  "Things in a bathroom",
  "Things in a bedroom",
  "Things in a garage",
  "Things in a classroom",
  "Things in a library",
  "Things in a museum",
  "Things at a playground",
  "Things at a park",
  "Things at a beach",
  "Things at an airport",
  "Things at a hotel",
  "Things at a movie theater",
  "Things at a carnival",
  "Things at a birthday party",
  "Things at a picnic",
  "Things in a toolbox",
  "Things in a first-aid kit",
  "Things on a desk",
  "Things in a car",
  "Things in a suitcase",
  "Places to go on vacation",
  "Cities",
  "Countries",
  "Places to eat",
  "Places to shop",
  "Places to exercise",
  "Places to take a picture",
  "Things you do outside",
  "Things you do on a rainy day",
  "Things you do at a party",
  "Things you do on a road trip",
  "Sports",
  "Sports equipment",
  "Board games",
  "Card games",
  "Video games",
  "Toys",
  "Hobbies",
  "Musical instruments",
  "Songs you can sing along to",
  "Singers and bands",
  "Movie titles",
  "TV shows",
  "Cartoon characters",
  "Fictional heroes",
  "Book titles",
  "Things in a fairy tale",
  "Things in outer space",
  "Things a robot could do",
  "Jobs",
  "Vehicles",
  "Things that fly",
  "Things that make noise",
  "Things that give off light",
  "Things you can draw",
  "Things you can photograph",
  "Things you can make with paper",
  "Things you can do with a ball",
  "Things you can put in a box"
]);

export const CATEGORY_PACKS = Object.freeze([
  {
    id: "classroom-safe",
    name: "Classroom Safe",
    description: "Familiar categories for a shared screen.",
    categories: Object.freeze(PROMPTS.map((prompt) => Object.freeze({
      id: prompt.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""),
      prompt,
      difficulty: "easy",
      minAnswers: 12
    })))
  }
]);

export const CLASSROOM_SAFE_PACK = CATEGORY_PACKS[0];

export function getCategoryById(id) {
  return CLASSROOM_SAFE_PACK.categories.find((category) => category.id === id) ?? null;
}

export function shuffleCategories(categories, random = Math.random) {
  const shuffled = [...categories];

  for (let index = shuffled.length - 1; index > 0; index -= 1) {
    const replacement = Math.floor(random() * (index + 1));
    [shuffled[index], shuffled[replacement]] = [shuffled[replacement], shuffled[index]];
  }

  return shuffled;
}
