import { ADDITIONAL_CARD_GROUPS } from "./additional-reviewed-cards.js";

// Each card has two clue routes: a direct description (three words) and a
// common setting, use, or association (two words). The UI shows all five.
export const CARD_GROUPS = [
  ["Food", [
    ["Pizza", ["cheese", "crust", "pepperoni"], ["slice", "delivery"]],
    ["Burger", ["bun", "beef", "patty"], ["fries", "ketchup"]],
    ["Taco", ["tortilla", "shell", "meat"], ["salsa", "Mexican"]],
    ["Sushi", ["rice", "seaweed", "fish"], ["Japan", "roll"]],
    ["Pasta", ["noodles", "Italian", "sauce"], ["spaghetti", "boil"]],
    ["Salad", ["lettuce", "greens", "dressing"], ["healthy", "bowl"]],
    ["Soup", ["broth", "liquid", "spoon"], ["chicken", "hot"]],
    ["Pancake", ["syrup", "breakfast", "stack"], ["griddle", "fluffy"]],
    ["Waffle", ["grid", "syrup", "breakfast"], ["iron", "crispy"]],
    ["Cereal", ["milk", "breakfast", "bowl"], ["box", "flakes"]],
    ["Toast", ["bread", "breakfast", "butter"], ["burnt", "toaster"]],
    ["Bagel", ["bread", "hole", "cream"], ["breakfast", "cheese"]],
    ["Donut", ["glaze", "hole", "sprinkles"], ["coffee", "bakery"]],
    ["Cookie", ["dough", "chip", "chocolate"], ["milk", "bake"]],
    ["Brownie", ["chocolate", "square", "fudge"], ["bake", "dessert"]],
    ["Muffin", ["bake", "blueberry", "breakfast"], ["cupcake", "paper"]],
    ["Cupcake", ["frosting", "cake", "small"], ["birthday", "sprinkles"]],
    ["Popcorn", ["kernel", "butter", "microwave"], ["movie", "theater"]],
    ["Candy", ["sweet", "sugar", "chocolate"], ["Halloween", "wrapper"]],
    ["Chocolate", ["cocoa", "brown", "sweet"], ["bar", "Valentine"]],
    ["Cheese", ["dairy", "milk", "yellow"], ["mouse", "pizza"]],
    ["Butter", ["spread", "milk", "yellow"], ["toast", "melt"]],
    ["Peanut", ["nut", "shell", "butter"], ["elephant", "allergy"]],
    ["Banana", ["yellow", "peel", "fruit"], ["monkey", "bunch"]],
    ["Apple", ["red", "fruit", "tree"], ["pie", "teacher"]],
    ["Orange", ["fruit", "citrus", "peel"], ["juice", "color"]],
    ["Lemon", ["yellow", "sour", "citrus"], ["lemonade", "squeeze"]],
    ["Strawberry", ["red", "berry", "seeds"], ["shortcake", "cream"]],
    ["Carrot", ["orange", "vegetable", "root"], ["rabbit", "crunch"]],
    ["Potato", ["vegetable", "starch", "peel"], ["fries", "mashed"]],
    ["Rice", ["grain", "white", "bowl"], ["sushi", "fried"]]
  ]],
  ["Places", [
    ["Kitchen", ["cook", "stove", "fridge"], ["house", "food"]],
    ["Bathroom", ["toilet", "shower", "sink"], ["towel", "mirror"]],
    ["Bedroom", ["bed", "sleep", "pillow"], ["closet", "night"]],
    ["Garage", ["car", "park", "tools"], ["house", "door"]],
    ["Library", ["books", "read", "quiet"], ["borrow", "librarian"]],
    ["School", ["teacher", "student", "classroom"], ["learn", "homework"]],
    ["Hospital", ["doctor", "nurse", "patient"], ["emergency", "surgery"]],
    ["Restaurant", ["menu", "waiter", "food"], ["reservation", "tip"]],
    ["Hotel", ["room", "lobby", "bed"], ["vacation", "checkout"]],
    ["Airport", ["plane", "flight", "security"], ["passport", "luggage"]],
    ["Beach", ["sand", "ocean", "waves"], ["sunbathe", "towel"]],
    ["Park", ["grass", "trees", "bench"], ["play", "picnic"]],
    ["Zoo", ["animals", "cages", "keeper"], ["lion", "exhibit"]],
    ["Museum", ["art", "exhibit", "history"], ["gallery", "ticket"]],
    ["Theater", ["stage", "actor", "curtain"], ["play", "audience"]],
    ["Stadium", ["sports", "crowd", "seats"], ["game", "team"]],
    ["Bank", ["money", "cash", "account"], ["teller", "loan"]],
    ["Bakery", ["bread", "cake", "pastry"], ["baker", "oven"]],
    ["Farm", ["animals", "crops", "barn"], ["tractor", "farmer"]],
    ["Playground", ["swing", "slide", "kids"], ["park", "sandbox"]],
    ["Supermarket", ["groceries", "cart", "aisle"], ["checkout", "cashier"]],
    ["Mall", ["shops", "stores", "food"], ["clothes", "shopping"]],
    ["Office", ["desk", "computer", "work"], ["boss", "meeting"]],
    ["Garden", ["flowers", "plants", "soil"], ["water", "vegetables"]],
    ["Classroom", ["teacher", "student", "desks"], ["school", "whiteboard"]],
    ["Basement", ["house", "downstairs", "stairs"], ["storage", "dark"]]
  ]],
  ["Animals", [
    ["Dog", ["bark", "puppy", "pet"], ["leash", "fetch"]],
    ["Cat", ["meow", "kitten", "pet"], ["purr", "litter"]],
    ["Horse", ["ride", "saddle", "mane"], ["stable", "gallop"]],
    ["Cow", ["moo", "milk", "farm"], ["beef", "udder"]],
    ["Pig", ["oink", "mud", "snout"], ["bacon", "farm"]],
    ["Sheep", ["wool", "lamb", "farm"], ["shepherd", "flock"]],
    ["Goat", ["horns", "beard", "farm"], ["cheese", "bleat"]],
    ["Lion", ["mane", "roar", "cat"], ["king", "Africa"]],
    ["Tiger", ["stripes", "orange", "cat"], ["jungle", "roar"]],
    ["Elephant", ["trunk", "tusks", "huge"], ["zoo", "peanuts"]],
    ["Giraffe", ["neck", "tall", "spots"], ["zoo", "Africa"]],
    ["Zebra", ["stripes", "horse", "black"], ["white", "Africa"]],
    ["Monkey", ["banana", "tail", "swing"], ["zoo", "jungle"]],
    ["Gorilla", ["ape", "strong", "chest"], ["jungle", "zoo"]],
    ["Bear", ["fur", "claws", "large"], ["honey", "hibernate"]],
    ["Penguin", ["black", "white", "bird"], ["ice", "waddle"]],
    ["Dolphin", ["ocean", "swim", "fin"], ["jump", "smart"]],
    ["Shark", ["teeth", "fin", "ocean"], ["jaws", "attack"]],
    ["Whale", ["huge", "ocean", "blowhole"], ["song", "mammal"]],
    ["Octopus", ["eight", "arms", "tentacles"], ["ink", "ocean"]],
    ["Frog", ["hop", "green", "pond"], ["croak", "tadpole"]],
    ["Snake", ["slither", "scales", "venom"], ["hiss", "bite"]],
    ["Butterfly", ["wings", "caterpillar", "colorful"], ["flowers", "cocoon"]],
    ["Bee", ["buzz", "honey", "sting"], ["hive", "flower"]],
    ["Owl", ["hoot", "bird", "night"], ["wise", "eyes"]]
  ]],
  ["Home", [
    ["Chair", ["sit", "seat", "legs"], ["table", "office"]],
    ["Table", ["flat", "legs", "surface"], ["dinner", "chairs"]],
    ["Couch", ["sofa", "sit", "cushions"], ["living", "television"]],
    ["Bed", ["sleep", "mattress", "pillow"], ["bedroom", "blanket"]],
    ["Pillow", ["head", "soft", "sleep"], ["bed", "case"]],
    ["Blanket", ["warm", "cover", "bed"], ["sleep", "couch"]],
    ["Lamp", ["light", "shade", "bulb"], ["desk", "nightstand"]],
    ["Mirror", ["reflection", "glass", "look"], ["bathroom", "face"]],
    ["Clock", ["time", "hands", "numbers"], ["wall", "alarm"]],
    ["Door", ["open", "close", "handle"], ["entrance", "knock"]],
    ["Window", ["glass", "pane", "view"], ["curtain", "outside"]],
    ["Key", ["unlock", "metal", "lock"], ["door", "ring"]],
    ["Lock", ["key", "secure", "door"], ["combination", "padlock"]],
    ["Refrigerator", ["cold", "food", "freezer"], ["kitchen", "milk"]],
    ["Oven", ["bake", "hot", "stove"], ["kitchen", "pizza"]],
    ["Microwave", ["heat", "food", "fast"], ["popcorn", "kitchen"]],
    ["Toaster", ["bread", "toast", "slot"], ["breakfast", "kitchen"]],
    ["Sink", ["water", "drain", "faucet"], ["dishes", "bathroom"]],
    ["Faucet", ["tap", "water", "sink"], ["hot", "cold"]],
    ["Broom", ["sweep", "bristles", "floor"], ["dustpan", "clean"]],
    ["Vacuum", ["suction", "carpet", "clean"], ["dust", "floor"]],
    ["Bucket", ["pail", "handle", "water"], ["mop", "sand"]],
    ["Sponge", ["absorb", "soft", "scrub"], ["dishes", "bath"]],
    ["Towel", ["dry", "cloth", "bath"], ["shower", "beach"]],
    ["Soap", ["wash", "clean", "bubbles"], ["shower", "hands"]]
  ]],
  ["Personal", [
    ["Phone", ["call", "text", "screen"], ["pocket", "ring"]],
    ["Wallet", ["money", "cards", "leather"], ["pocket", "pay"]],
    ["Purse", ["bag", "carry", "handbag"], ["wallet", "shoulder"]],
    ["Backpack", ["bag", "straps", "carry"], ["school", "hiking"]],
    ["Umbrella", ["rain", "open", "cover"], ["wet", "handle"]],
    ["Sunglasses", ["eyes", "sun", "shades"], ["summer", "beach"]],
    ["Watch", ["time", "wrist", "clock"], ["strap", "wear"]],
    ["Ring", ["finger", "jewelry", "circle"], ["wedding", "diamond"]],
    ["Necklace", ["neck", "chain", "jewelry"], ["pendant", "gift"]],
    ["Hat", ["head", "wear", "brim"], ["sun", "baseball"]],
    ["Shoes", ["feet", "wear", "laces"], ["walk", "pair"]],
    ["Jacket", ["coat", "zipper", "warm"], ["outside", "cold"]],
    ["Gloves", ["hands", "fingers", "warm"], ["winter", "snow"]],
    ["Scarf", ["neck", "wrap", "warm"], ["winter", "fashion"]],
    ["Toothbrush", ["teeth", "brush", "paste"], ["bathroom", "morning"]],
    ["Comb", ["hair", "teeth", "style"], ["bathroom", "pocket"]],
    ["Hairbrush", ["hair", "bristles", "tangles"], ["mirror", "style"]],
    ["Razor", ["shave", "blade", "hair"], ["bathroom", "beard"]],
    ["Perfume", ["smell", "scent", "spray"], ["bottle", "gift"]],
    ["Lipstick", ["lips", "makeup", "color"], ["red", "kiss"]]
  ]],
  ["Nature", [
    ["Rain", ["water", "cloud", "wet"], ["umbrella", "puddle"]],
    ["Snow", ["white", "cold", "flakes"], ["winter", "snowman"]],
    ["Thunder", ["loud", "storm", "rumble"], ["lightning", "sky"]],
    ["Lightning", ["flash", "storm", "electric"], ["thunder", "sky"]],
    ["Rainbow", ["colors", "arc", "sky"], ["rain", "sun"]],
    ["Sun", ["bright", "hot", "star"], ["day", "summer"]],
    ["Moon", ["night", "sky", "round"], ["crater", "space"]],
    ["Star", ["sky", "twinkle", "bright"], ["night", "wish"]],
    ["Cloud", ["white", "sky", "fluffy"], ["rain", "float"]],
    ["Wind", ["blow", "air", "breeze"], ["kite", "storm"]],
    ["Tornado", ["twister", "funnel", "storm"], ["wind", "shelter"]],
    ["Volcano", ["lava", "eruption", "mountain"], ["ash", "hot"]],
    ["Earthquake", ["ground", "shake", "tremor"], ["buildings", "fault"]],
    ["Mountain", ["high", "peak", "climb"], ["snow", "hiking"]],
    ["River", ["water", "flow", "stream"], ["bank", "bridge"]],
    ["Ocean", ["sea", "salt", "water"], ["waves", "beach"]],
    ["Forest", ["trees", "woods", "green"], ["animals", "hiking"]],
    ["Desert", ["sand", "dry", "hot"], ["cactus", "camel"]],
    ["Island", ["land", "water", "surrounded"], ["beach", "boat"]],
    ["Waterfall", ["water", "falls", "cliff"], ["river", "mist"]]
  ]],
  ["People", [
    ["Teacher", ["school", "students", "class"], ["homework", "lesson"]],
    ["Doctor", ["medicine", "patient", "hospital"], ["stethoscope", "checkup"]],
    ["Nurse", ["hospital", "patient", "care"], ["doctor", "uniform"]],
    ["Chef", ["cook", "kitchen", "food"], ["restaurant", "hat"]],
    ["Waiter", ["restaurant", "serve", "tables"], ["menu", "tip"]],
    ["Pilot", ["plane", "fly", "cockpit"], ["airport", "uniform"]],
    ["Driver", ["car", "steer", "road"], ["bus", "license"]],
    ["Farmer", ["farm", "crops", "tractor"], ["barn", "animals"]],
    ["Firefighter", ["fire", "hose", "rescue"], ["truck", "helmet"]],
    ["Officer", ["police", "badge", "law"], ["arrest", "uniform"]],
    ["Artist", ["paint", "draw", "creative"], ["canvas", "gallery"]],
    ["Singer", ["song", "voice", "sing"], ["microphone", "concert"]],
    ["Dancer", ["dance", "moves", "music"], ["stage", "ballet"]],
    ["Actor", ["movie", "role", "perform"], ["stage", "camera"]],
    ["Athlete", ["sports", "train", "compete"], ["team", "medal"]],
    ["Dentist", ["teeth", "clean", "cavity"], ["drill", "appointment"]],
    ["Barber", ["hair", "cut", "clippers"], ["shop", "chair"]],
    ["Librarian", ["books", "library", "quiet"], ["borrow", "shelves"]],
    ["Plumber", ["pipes", "water", "fix"], ["sink", "leak"]],
    ["Mechanic", ["car", "repair", "engine"], ["garage", "tools"]]
  ]],
  ["Actions", [
    ["Running", ["fast", "legs", "exercise"], ["race", "shoes"]],
    ["Swimming", ["water", "pool", "stroke"], ["beach", "goggles"]],
    ["Dancing", ["music", "moves", "rhythm"], ["party", "floor"]],
    ["Singing", ["voice", "song", "lyrics"], ["karaoke", "shower"]],
    ["Cooking", ["food", "kitchen", "recipe"], ["stove", "dinner"]],
    ["Baking", ["oven", "cake", "dough"], ["cookies", "flour"]],
    ["Shopping", ["buy", "store", "money"], ["cart", "mall"]],
    ["Sleeping", ["bed", "tired", "night"], ["dream", "pillow"]],
    ["Reading", ["book", "words", "pages"], ["library", "glasses"]],
    ["Writing", ["pen", "paper", "letters"], ["story", "homework"]],
    ["Painting", ["brush", "color", "canvas"], ["wall", "artist"]],
    ["Cleaning", ["dirty", "wash", "scrub"], ["house", "soap"]],
    ["Hiking", ["walk", "trail", "mountain"], ["boots", "backpack"]],
    ["Camping", ["tent", "outside", "woods"], ["fire", "sleeping"]],
    ["Fishing", ["fish", "rod", "hook"], ["lake", "boat"]],
    ["Driving", ["car", "road", "steering"], ["license", "traffic"]],
    ["Flying", ["air", "plane", "wings"], ["pilot", "sky"]],
    ["Laughing", ["funny", "joke", "smile"], ["comedy", "giggle"]],
    ["Crying", ["tears", "sad", "eyes"], ["tissue", "emotion"]],
    ["Sneezing", ["nose", "achoo", "allergy"], ["tissue", "bless"]]
  ]],
  ["Entertainment", [
    ["Movie", ["film", "screen", "actors"], ["theater", "popcorn"]],
    ["Television", ["screen", "shows", "watch"], ["remote", "couch"]],
    ["Radio", ["music", "station", "broadcast"], ["car", "antenna"]],
    ["Podcast", ["audio", "episode", "listen"], ["host", "headphones"]],
    ["Book", ["pages", "read", "cover"], ["library", "author"]],
    ["Comic", ["pictures", "panels", "speech"], ["superhero", "book"]],
    ["Cartoon", ["animated", "drawing", "character"], ["children", "television"]],
    ["Concert", ["music", "live", "band"], ["tickets", "crowd"]],
    ["Music", ["song", "sound", "rhythm"], ["radio", "dance"]],
    ["Guitar", ["strings", "strum", "instrument"], ["band", "rock"]],
    ["Piano", ["keys", "instrument", "play"], ["concert", "grand"]],
    ["Drums", ["beat", "sticks", "instrument"], ["band", "loud"]],
    ["Camera", ["picture", "lens", "photo"], ["flash", "vacation"]],
    ["Photograph", ["picture", "image", "snapshot"], ["camera", "frame"]],
    ["Video", ["moving", "record", "screen"], ["camera", "online"]],
    ["Karaoke", ["sing", "lyrics", "microphone"], ["bar", "music"]],
    ["Circus", ["clown", "tent", "acrobat"], ["animals", "show"]],
    ["Magic", ["trick", "illusion", "wand"], ["rabbit", "hat"]],
    ["Puzzle", ["pieces", "solve", "picture"], ["jigsaw", "table"]],
    ["Chess", ["king", "queen", "board"], ["checkmate", "pawn"]]
  ]],
  ["Sports", [
    ["Soccer", ["ball", "goal", "kick"], ["field", "team"]],
    ["Basketball", ["hoop", "ball", "dribble"], ["court", "basket"]],
    ["Baseball", ["bat", "ball", "pitch"], ["home", "inning"]],
    ["Football", ["touchdown", "ball", "helmet"], ["quarterback", "field"]],
    ["Tennis", ["racket", "ball", "net"], ["court", "serve"]],
    ["Golf", ["club", "ball", "hole"], ["course", "putt"]],
    ["Hockey", ["puck", "stick", "ice"], ["rink", "goalie"]],
    ["Boxing", ["punch", "gloves", "ring"], ["fight", "knockout"]],
    ["Bowling", ["pins", "ball", "lane"], ["strike", "shoes"]],
    ["Yoga", ["stretch", "pose", "mat"], ["breathe", "exercise"]],
    ["Skateboard", ["wheels", "board", "ride"], ["trick", "park"]],
    ["Surfing", ["wave", "board", "ocean"], ["beach", "wetsuit"]],
    ["Skiing", ["snow", "slopes", "skis"], ["mountain", "lift"]],
    ["Marathon", ["run", "long", "race"], ["finish", "miles"]],
    ["Gymnastics", ["flip", "balance", "tumble"], ["beam", "olympics"]],
    ["Volleyball", ["net", "ball", "spike"], ["beach", "serve"]],
    ["Wrestling", ["grapple", "mat", "pin"], ["ring", "match"]],
    ["Cycling", ["bike", "pedal", "ride"], ["helmet", "road"]],
    ["Racing", ["fast", "speed", "finish"], ["cars", "track"]],
    ["Darts", ["throw", "target", "board"], ["bullseye", "pub"]]
  ]],
  ["Technology", [
    ["Computer", ["screen", "keyboard", "mouse"], ["work", "internet"]],
    ["Laptop", ["computer", "portable", "screen"], ["keyboard", "battery"]],
    ["Keyboard", ["keys", "type", "letters"], ["computer", "desk"]],
    ["Mouse", ["click", "cursor", "computer"], ["desk", "wireless"]],
    ["Monitor", ["screen", "display", "computer"], ["desk", "pixels"]],
    ["Printer", ["paper", "ink", "print"], ["office", "computer"]],
    ["Internet", ["online", "web", "connection"], ["browser", "search"]],
    ["Website", ["page", "online", "browser"], ["address", "click"]],
    ["Email", ["message", "send", "inbox"], ["address", "spam"]],
    ["Password", ["secret", "login", "letters"], ["account", "reset"]],
    ["Robot", ["machine", "metal", "program"], ["future", "automate"]],
    ["Drone", ["fly", "camera", "remote"], ["sky", "propeller"]],
    ["Battery", ["power", "charge", "energy"], ["phone", "remote"]],
    ["Charger", ["battery", "power", "cable"], ["phone", "outlet"]],
    ["Wifi", ["wireless", "internet", "signal"], ["router", "password"]],
    ["Satellite", ["space", "orbit", "signal"], ["dish", "television"]],
    ["Telescope", ["stars", "lens", "far"], ["moon", "astronomy"]],
    ["Microscope", ["tiny", "lens", "magnify"], ["lab", "cells"]],
    ["Headphones", ["ears", "listen", "music"], ["wireless", "phone"]],
    ["Speaker", ["sound", "loud", "music"], ["bluetooth", "party"]]
  ]],
  ["Travel", [
    ["Airplane", ["fly", "wings", "pilot"], ["airport", "flight"]],
    ["Train", ["tracks", "cars", "rail"], ["station", "ticket"]],
    ["Bus", ["passengers", "driver", "seats"], ["stop", "school"]],
    ["Subway", ["underground", "train", "station"], ["city", "commute"]],
    ["Bicycle", ["pedals", "wheels", "ride"], ["helmet", "exercise"]],
    ["Motorcycle", ["engine", "two", "wheels"], ["helmet", "ride"]],
    ["Car", ["drive", "wheels", "engine"], ["road", "gas"]],
    ["Boat", ["water", "float", "sail"], ["lake", "fishing"]],
    ["Ship", ["boat", "large", "ocean"], ["cruise", "cargo"]],
    ["Taxi", ["car", "ride", "fare"], ["driver", "city"]],
    ["Passport", ["travel", "photo", "identity"], ["airport", "border"]],
    ["Suitcase", ["bag", "pack", "clothes"], ["airport", "vacation"]],
    ["Map", ["directions", "roads", "location"], ["travel", "fold"]],
    ["Ticket", ["entry", "paper", "pass"], ["concert", "train"]],
    ["Luggage", ["bags", "travel", "suitcase"], ["airport", "carousel"]],
    ["Vacation", ["trip", "travel", "relax"], ["beach", "hotel"]],
    ["Tourist", ["visitor", "travel", "sightsee"], ["camera", "map"]],
    ["Cruise", ["ship", "ocean", "vacation"], ["buffet", "port"]],
    ["Highway", ["road", "cars", "fast"], ["exit", "traffic"]],
    ["Traffic", ["cars", "jam", "road"], ["commute", "lights"]]
  ]],
  ["Life", [
    ["Birthday", ["cake", "candles", "age"], ["party", "presents"]],
    ["Wedding", ["bride", "groom", "marriage"], ["ring", "ceremony"]],
    ["Graduation", ["school", "diploma", "degree"], ["cap", "ceremony"]],
    ["Party", ["guests", "celebrate", "music"], ["birthday", "dance"]],
    ["Holiday", ["celebrate", "special", "calendar"], ["Christmas", "vacation"]],
    ["Gift", ["present", "wrapped", "give"], ["birthday", "surprise"]],
    ["Surprise", ["unexpected", "shock", "secret"], ["party", "gift"]],
    ["Secret", ["hidden", "private", "tell"], ["whisper", "surprise"]],
    ["Friend", ["person", "like", "close"], ["play", "trust"]],
    ["Family", ["parents", "children", "relatives"], ["home", "reunion"]],
    ["Baby", ["infant", "small", "newborn"], ["diaper", "cry"]],
    ["Job", ["work", "employed", "career"], ["boss", "salary"]],
    ["Interview", ["questions", "answers", "meeting"], ["job", "hire"]],
    ["Meeting", ["people", "talk", "gather"], ["office", "schedule"]],
    ["Date", ["romance", "couple", "dinner"], ["calendar", "month"]],
    ["Picnic", ["outside", "food", "blanket"], ["park", "basket"]],
    ["Dinner", ["meal", "evening", "eat"], ["table", "restaurant"]],
    ["Breakfast", ["morning", "meal", "eat"], ["eggs", "cereal"]],
    ["Lunch", ["midday", "meal", "eat"], ["sandwich", "school"]],
    ["Bedtime", ["night", "sleep", "pajamas"], ["story", "lights"]],
    ["Dream", ["sleep", "imagine", "night"], ["wish", "nightmare"]]
  ]],
  ["Toys", [
    ["Monopoly", ["board", "money", "property"], ["hotel", "jail"]],
    ["Scrabble", ["letters", "tiles", "words"], ["board", "points"]],
    ["Checkers", ["board", "pieces", "jump"], ["red", "black"]],
    ["Dice", ["roll", "numbers", "cubes"], ["game", "chance"]],
    ["Cards", ["deck", "shuffle", "suits"], ["poker", "ace"]],
    ["Doll", ["toy", "figure", "dress"], ["Barbie", "child"]],
    ["Ball", ["round", "bounce", "throw"], ["sports", "catch"]],
    ["Kite", ["fly", "string", "wind"], ["sky", "park"]],
    ["Teddy", ["bear", "stuffed", "soft"], ["bed", "child"]],
    ["Swing", ["seat", "back", "forth"], ["playground", "push"]],
    ["Slide", ["down", "slippery", "climb"], ["playground", "kids"]],
    ["Sandbox", ["sand", "box", "play"], ["shovel", "playground"]],
    ["Marbles", ["glass", "small", "round"], ["game", "roll"]],
    ["Balloon", ["air", "inflate", "float"], ["party", "pop"]],
    ["Frisbee", ["disc", "throw", "catch"], ["park", "dog"]]
  ]],
  ["Clothing", [
    ["Shirt", ["wear", "sleeves", "top"], ["buttons", "closet"]],
    ["Pants", ["legs", "wear", "waist"], ["jeans", "pockets"]],
    ["Dress", ["wear", "skirt", "outfit"], ["wedding", "closet"]],
    ["Skirt", ["waist", "wear", "hem"], ["dress", "school"]],
    ["Socks", ["feet", "pair", "wear"], ["shoes", "laundry"]],
    ["Boots", ["shoes", "feet", "tall"], ["rain", "winter"]],
    ["Sneakers", ["shoes", "laces", "athletic"], ["running", "gym"]],
    ["Hoodie", ["sweatshirt", "hood", "warm"], ["pocket", "casual"]],
    ["Sweater", ["knit", "warm", "wool"], ["winter", "closet"]],
    ["Coat", ["jacket", "warm", "outer"], ["winter", "closet"]],
    ["Tie", ["neck", "knot", "formal"], ["suit", "office"]],
    ["Belt", ["waist", "buckle", "pants"], ["leather", "holes"]],
    ["Pajamas", ["sleep", "night", "clothes"], ["bed", "bedtime"]],
    ["Uniform", ["matching", "outfit", "wear"], ["school", "work"]],
    ["Costume", ["dress", "disguise", "character"], ["Halloween", "party"]],
    ["Crown", ["head", "royal", "gold"], ["king", "queen"]],
    ["Apron", ["wear", "protect", "front"], ["cook", "kitchen"]],
    ["Swimsuit", ["wear", "water", "swim"], ["beach", "pool"]],
    ["Raincoat", ["wear", "waterproof", "jacket"], ["umbrella", "storm"]],
    ["Helmet", ["head", "protect", "hard"], ["bike", "sports"]]
  ]],
  ...ADDITIONAL_CARD_GROUPS
];
